---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgBQ07oSsgtlbDNnNV2Px9/2AjUrlCo+2fpDlLsDjTZQ/3dfbx2c+QevNzgOPITUXCTbQYBvL7CyutbCRLZWdDWv5oDGsa7B5jdbhcJpJXUtgaXBZaHgkoS6oX1OcN7vHoEoa+MkIH7ARKCgUgY5p/Dp5XTb3FUcRpaekwBN6EriOoxQNk74dmAA828n/dn5Mcicl3Ame1Lj8CEkRl6pw6trLZBegFOw7FNotQ9byMunqhwbEIFykz6nrkPvx/8hcytymuAsz6VEWjTFxgRZijQt+dDM0BeIBla6g40rCMVWGrcsIrkYZs98Y5+vavaIJ6C6tCJDbaW2WdTZ87/qPI1Zz+zWdg4VM9VUmYw9BoKvZbdLy2spDhUrB4lyra6ZQMrT0wX5TJbufC4DexPJa5ouMpIAbTemrsgSyJzidEKL5vKrY2/TTG5UgzQKnfbCEUi7a1taLws3bjVxtc3JQwIEPjvNO2eLgwYCXi91uk288uABe+uXXgMH3CRIzOD2+DdRVk8MSFCKvyHOyaRlfyYkGiBHnCfpGce7yEIRvVt6QlMCjEp02vftqciP5TAFVZRuYxKU7Z+rw/GOIPqtPWi9TStC6Og73bBWDjRzT7ZOGygPTEakKckEGqrb/ArtEM9fQIq9YPQ7pSiJkFMQdMr/b/gOHgNpcMCbcZF52GDuJ9fPdFedmhqE/4slGLJ8u4E8fUwnHtowAZ5hvpYrXQ==
    username: AgB5kc/0jn3I+a1AS3355+xLTdHCuGdfMlmI3gX/YNvbndgbPlL6spHtzs2Dh3fSUfTLqzltxsAzGc4/G9KxF1lArZZFBhB6RGuepufIjhbiPIAhKfnlvzQ5yd3rFnlF+Lo/JyA/ssv3se7I603uYovXja/YryrVNhRZrpsdFGky7m5XGQgWp6uS+8WuZ7L8mGyvxv3hcJ1NEL//R5w/xd/DdTBhGWe+bVbXWifTQfoO1Lpz47qU9l8n01Z1ROjP7EbYNyS0ZwuBLQyoLrnnaSIef/NwFdEGeqW+/xDxJX1tA8VooiGdiWYGRcfqzVX8Ezf8rwRzriEkNICRbGXLKfpd3M9vaCd7uQSnpwIvm3gyqtgRgnBO93jaK+1Wg5qJUM8ST8bhNkNhP/hKkjC8CHzRUfxrplowrie8fDWwsnn9aMRnebRaStgzfSqX3DsPDIJYYvTDH1srMNrDGuD8JQM8Nn3DDxlTi0yesCyhRrws3/sdI91yJBoRxbPg8tKemsNfoPFaPmcnJRMtjjI/XSEXLfxHAbzMNeikK8WiehgcaiInJc/RBQZBuxYwdURb8EIJEInPzTjNJBrxlYFEdobQDPMwjrqFFyTVGMFgs/DN1YSDnP8YGEHbZYFqY2U90s7WroM+XsAo+KKOQr8rHU6SQeliiYGPbHKC1LfFOThS23iu/cmwID0vooDiddhL2IVyVR6dPw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-credentials
      namespace: prod
