---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: prod
spec:
  encryptedData:
    access-key: AgAZXq5agfAiwVgLuAGNTKvGzoD9V+tndKTjoNdBGuTAHMAxnB4m07qLGNH4E9Div8FuJf9/2M/P/GZ3ajsyP2VX+OL/FUMfUvjD6XsCc5h6ga5TJGeZdjU5k3KqTIxOyUEBi4i0AQVPBH+vPJO0A/q3W5AnndT/VOIDBz+Q3U9imIfNJVw34NAh/pA1bNzc3IQnTJpSzMsL3+9UrZ5zJ9dhPK+6erd3UodUdEv3MfssHQ6TJ0/90gDa9Vx/Oc0I5hYaHBXF2s4Mlhf8wQJGjfhWDTF1MpTI9smOsBzp5hQJMJv6eW/y+xpgJoyfY0PR+BrVGfY4WjjpeRTmH3Bm6eQ16hycsAQCM/BG4aUpBF2a/WHVqhjVmkDxFSaB3NA7VRFsCuNH/S+ZSr6uUeXcbi3eLXktrT7wnDFu+W+0dxkk2URFhvq0fPUSsdGPlPamhPLtoSHostM/CQWMrcmnFquEXwcCh2MA19W+0j4YiEgoBYeBDse01J/jLlAefdWpAmXrxZ2zYGHtNkvhhKnGeZgWUMWectTWkyzhRFHDqZcdz6NHsLjUahtuWZr238LkphvnDn6F6IU32gxejcF5QXPOoKtta3QzbHWe1Bu9mzfz1iyWt96jjxCKTmGLUY0C5ml1IM0lqXu4f6tKoFuyFgwjHJLXc/NxS/4BMu/h58SKdILKokfGtiNGMZ+dURLiELtrgLDJ+g==
    secret-key: AgCP0N61V1XouuPlkC9QbmEnoGn9/SgmDMG6wjJiaqVyRiLJ8k9XSG82aJAmY4UukNwGZVRk7cGgiCSyzFxUxhY4HuZ32MEt/fFNSa/jwwgnv6klgzRC05reVXInTkvRiEOx2+YHJGd0ty8UUxa8itMCZfAzipAZaLY3PfnUG9afJ2V1amrijhmz0Z7A/jZY7KbrJXV74sjBeLdqtviXhJrlgQpypVUq+XINFIGuP95wLjHis9kXk0MaXpSz5CezS8DyvdCl2IYWS/r9z4czvedQPkd+fCYh4droHY8tdNPDLgwEjQC/xS8l/rrpdGRpFY3HDN23fYR5fFfSY0Rrf6sZPau759ntILs0S1g5lNYFngebb4tZs/atRH8AQQxqfPoPsSbnZyJs9C/lIZusOggEo7wE/DvYY5xRQDnD9qzBayXlR7VACDrh07+CTqcLIH0v29DJcw9C+V5+K0rtjPp2kZZNka3f4taY6RqmtHWyha5SoZWpKn5XajM2B/gEG9eVK+aYnx3PKebXL90PuRSmnS8HdwqbfEeELE09T6m6vKZnYdOQAqn97Su4r/QDvC6aYrilKMz43u6jV6H5U8lUV1tVb72qbfpCtUh8eX0/XLdArH16M00JJKb++g88CKK51h/9etUiQ4AOuasF1MGVjR/atr2ast3TXrwb/hdvErBgM2V6eNIdetPdQDzEVq4Hv5MIUqixox4rlbFThw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: prod
