---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBBrh/svJYqQpasAzaOBx5QgleR5ypwD3OxNCwRkWw4GpN3M2vVOdDRy4omFH9ktml2S/vbJ7YFio8FF/baP6EY7azwRAfvOyDXk/weMvxykL+fxgL4fQRCBG/cx4VvHxLrl+doo9CCoANCxS33pXDQhnFvtQ5r+dGvWadOF2WI0r8LzwrqG9+b5X5gC0xUWxV8BSWzYo6L1WT4b9re9tJ4NYEhXNmKGeGJHL4HkULMQt/AoMpuAqw0uSsMQEAY2zFZHfKrIpidMiCIamsbJJsrKGqt7Xcwt3q4lVr6E6t3CBg8MlKqx9qtjEN1f35BIj7rZ6IeZbLlPyI5+Xj1VdIaHA0etncZ9+hILgUvyxNKi5m3FUQFM65MF2K6Nq64weZoc6YcmFuvBUkfqlpoNZdpIhxc4EjQ1f3UbJRqMFOYaAevBoaWI6vI6TgNb59SkzIdKn3IkdBkOH4HdPNThS3Asl0B6X+AqrAb2lYqE4cK+DkD4QuPryjTicWzBDiMkdImP37QALurUnho8GwmnwOtJJL7w0mfa5yXa2n50IXPDe9MxW9Ppp2IM+zU50Tf5Z2tWQnYfhcCO9pOI50Zg+UA3w62FOlG1BScnz25d+a2DP6gZtCf4+CnIr6G9WIL6pIQqD0h4rzZWuo6utHPr8scuWWewG1ve3+hJnsVpYgzC32+R6UDn7CCkJrndw7R3nVwDqV3wtVWqIrO7N1HFA==
    admin-user: AgB7cSOzjWT3bqFL3U7J9MXkR1UVpWR5JGn4kd/Xllbzmeys53Acsq0yvc/d6CKA/QAJjEs6wVRs3i4bylJSWWUfJDnTm8+te6WUjPd0IEZrGVu+S3y1gU1dARMu7UVX8LKchw7gThan/7k+f6bGe2ps6nbin2ePGdAdX7HjY/3lwiSd6NA9GS/295HrpVxZWrA9ovoqjhM89ZiCBEBXQTqaRgiXh8gl7ZXAUmu+x8UuWUxyns3N/JMLBW+3v47bcxnPomFQSJ+RqVOQzH8IgTKU2DE67kydgSVqQDBcwe6zIneHanzaI0y0KhqYWk7qiTis8A2FlJVtW9ZVnuHRa6YYDhhfzwAfQHSR71gDLZ3MZthT5LHz4/4j21AlYjnLd99o7OVTGzDJC9f2i1pGA/5Ix9gVSXSOU4OFR8TkCYX0DOV9gWy998JiXgacztMYymrWdjFvSXd+pbi0tpxundigoTkjyHTVYztotkPyYBfFJp3b8ZMEVcJojGnfaV27nVDI+6jJvO2GZeVZjdsEXU93FJtTriXUC7/AH4eUvBYXkovB94IzODd1aGbicPiKQNmz8wBCN4/BPY2JYaq5NWESR/uXnO0KSKqCUgYWsi6n6cD3EQzMDp8XZRmUraaMm9TziXa9ajCdlXgx80A2cLtedMTMnyQRzEe9QzeVxDRGnJiWf6wVn2s+eKlYzPEKeOyyB42ZJg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
