apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: ci-cd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 56.21.0
    helm:
      values: |
        grafana:
          admin:
            existingSecret: "grafana-admin-credentials"
            userKey: "admin-user"
            passwordKey: "admin-password"
          grafana.ini:
            auth.generic_oauth:
              enabled: true
              name: Keycloak
              allow_sign_up: true
              client_id: grafana
              client_secret: "2HxykeWpLFZGUoh5H7o4ABAuzqMGO6oh"
              scopes: openid profile email
              auth_url: http://192.168.1.101:30080/realms/yass/protocol/openid-connect/auth
              token_url: http://192.168.1.101:30080/realms/yass/protocol/openid-connect/token
              api_url: http://192.168.1.101:30080/realms/yass/protocol/openid-connect/userinfo  
        prometheus:
          prometheusSpec:
            retention: 7d
        alertmanager:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
