---
# 1. L'IDENTITÉ : On crée le compte de service pour le script Python
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ia-manager-sa
  namespace: ai-agent

---
# 2. LES DROITS : On définit ce qu'il a le droit de lire sur tout le cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ia-cluster-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"] # AUCUN droit de modification !
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]

---
# 3. L'ATTRIBUTION : On donne le rôle au compte de service
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ia-read-all-binding
subjects:
  - kind: ServiceAccount
    name: ia-manager-sa
    namespace: ai-agent
roleRef:
  kind: ClusterRole
  name: ia-cluster-reader
  apiGroup: rbac.authorization.k8s.io
